server:
  port: 7000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service

  cloud:
    gateway:
      routes:
        - id: fastapi-pdf-service
          uri: lb://FASTAPI-PDF-SERVICE
          predicates:
            - Path=/pdf/**
        - id: default
          uri: http://localhost:7000
          predicates:
            - Path=/**
      discovery:
        locator:
          enabled: true
